apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent-manager
  namespace: system
  labels:
    control-plane: agent-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: agent-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: scaleway-external-ip
    app.kubernetes.io/part-of: scaleway-external-ip
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: agent-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: agent-manager
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      containers:
      - command:
        - /manager
        args:
        - --agent-mode
        - --metrics-bind-address=127.0.0.1:8080
        - --health-probe-bind-address=127.0.0.1:8081
        image: controller:latest
        name: manager
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            host: 127.0.0.1
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
            host: 127.0.0.1
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: agent-manager
      terminationGracePeriodSeconds: 10
