apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: controller-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scaleway-external-ip
    app.kubernetes.io/part-of: scaleway-external-ip
    app.kubernetes.io/managed-by: kustomize
  name: controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: agent-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scaleway-external-ip
    app.kubernetes.io/part-of: scaleway-external-ip
    app.kubernetes.io/managed-by: kustomize
  name: agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-role
subjects:
- kind: ServiceAccount
  name: agent-manager
  namespace: system
