apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scaleway-external-ip
    app.kubernetes.io/part-of: scaleway-external-ip
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: agent-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scaleway-external-ip
    app.kubernetes.io/part-of: scaleway-external-ip
    app.kubernetes.io/managed-by: kustomize
  name: agent-manager
  namespace: system
